sonar.projectKey=mi-pipeline-calidad
sonar.organization=davidelezg-lab
sonar.projectName=mi-pipeline-calidad
sonar.projectVersion=1.0

sonar.sources=main.cpp
sonar.tests=test.cpp

sonar.cfamily.gcov.reportsPath=.

sonar.exclusions=**/*.exe,**/*.dll,**/*.obj,**/*.o,**/.scannerwork/**,**/build-wrapper-dump.json

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
